### ISSUE TITLE
Update samples to gltf2.0 specification

### ISSUE THREAD

**Issue by jtorresfabra** [CesiumGS/3d-tiles-samples#15]
We are trying to integrate 3D tiles in http://osgjs.org. Unfortunately we can't support all versions of glTF so it would be nice if the samples can be upgraded to glTF 2.0. Thanks!

**Comment by lilleyse** [comment]
Yes definitely, the 3D Tiles spec will ultimately be written against gltf 2.0. These samples should be updated relatively soon.

**Comment by pjcozzi** [comment]
@jtorresfabra in the meantime, there is a glTF 1.0 to 2.0 stage here: https://github.com/AnalyticalGraphicsInc/gltf-pipeline/pull/191

Also, see https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/94

**Comment by jtorresfabra** [comment]
Hi @lilleyse @pjcozzi Any news on this?

**Comment by lilleyse** [comment]
Sorry, no update yet. Since glTF 2.0 is now stabilized in Cesium we should be able to safely work on this.

**Comment by jtorresfabra** [comment]
Thanks, I will wait for it :).

**Comment by PrincessGod** [comment]
Hi, @lilleyse. 
I am using Cesium, and I want to convert my models to `b3dm`, but the spec using `batchId` with glTF 1.0,
so I am wondering if it possible to update both the 3d-tiles spec and Cesium support glTF 2.0 ?
thanks.

**Comment by lilleyse** [comment]
You can start to write `b3dm` tiles with glTF 2.0 already. Just ignore the notes in the spec for now that are relevant to glTF 1.0. As long as the glTF primitive has a `_BATCHID` vertex attribute, it should work.

Check out https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Specs/Data/Cesium3DTiles/Batched/BatchedWithKHRMaterialsCommon. While that tileset is not glTF 2.0, the idea is similar because that tile does not have shaders/techniques built-in.

**Comment by PrincessGod** [comment]
@lilleyse Thank you very mach! It is really helpful.

**Comment by PrincessGod** [comment]
@lilleyse Sorry to bother you again.

I have a standard glTF 2.0 model with _BATCHID now, but how can I convert to `.glb`? Cause I need convert it to `.b3dm` now. Thanks.

**Comment by lilleyse** [comment]
Keep an eye on the `2.0` branch in `gltf-pipeline`. The code is all there for converting glTF to glb but the CLI is not yet ready. I hope to update that soon and will get back to you when it's ready.

https://github.com/AnalyticalGraphicsInc/gltf-pipeline/tree/2.0

**Comment by PrincessGod** [comment]
@lilleyse Actually I found your `obj2gltf`, and my job is finished based on that, because it is glTF 2.0.
When I got `.glb` with `_BATCHID` build in, the `3d-tiles` formats all work out now! 

Thakns again, wishing you and Cesium having a great success.

**Comment by jucamal** [comment]
Hello, do you update the sample models to gltf 2.0?? 
I have been tried to convert using [https://github.com/AnalyticalGraphicsInc/3d-tiles-tools] but the model still on gltf 1.0.
I tested with TilesetWithDiscreteLOD

**Comment by lilleyse** [comment]
Sorry, the sample models have not been updated yet.
