### ISSUE TITLE
How can show my tile hierarchically?

### ISSUE THREAD

**Issue by learnerandtrainer** [CesiumGS/3d-tiles-samples#32]
Hi,
I created tileset acording to google gridtile,and I want to show my b3dm files over the json files because of my tile creation scenario. I created tilejson with 15 level of grid and set b3dm file then I added another girt tile json files as childs of b3dm in children property. But when I showing them on cessium only 15 level I saw . I dont know where is my pfault. Can any one help me?
Here is my tile set
[15.zip](https://github.com/CesiumGS/3d-tiles-samples/files/7329707/15.zip)
[16.zip](https://github.com/CesiumGS/3d-tiles-samples/files/7329708/16.zip)
[17.zip](https://github.com/CesiumGS/3d-tiles-samples/files/7329709/17.zip)
[18.zip](https://github.com/CesiumGS/3d-tiles-samples/files/7329710/18.zip)
in my scenario 15 level must link 16 and then other evel must show another. I had to upload one by one due to upload limit

And also this is result I saw
![image](https://user-images.githubusercontent.com/66632022/136952533-bb1e371c-372d-4064-b14c-af18cc4afc2d.png)
thanks in advance

**Comment by learnerandtrainer** [comment]
Also I created json file like "TilesetWithDiscreteLOD" example, but cesium didnt show 17 level b3dm file. Any one why it doesnt work
[15.zip](https://github.com/CesiumGS/3d-tiles-samples/files/7335657/15.zip)

**Comment by lilleyse** [comment]
Hi @learnerandtrainer. Sorry for missing your questions earlier. If you're still having trouble could you post your question on the [Cesium Community Forum](https://community.cesium.com/)?
