### ISSUE TITLE
MetadataGranularities validation failure

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/3d-tiles-samples#44]
`MetadataGranularities` is failing validation: `Tileset must define refine property in root tile`.

I think it would make sense for the root tile to be "ADD" and the children tiles to be not specify the refinement (and thus inherit "ADD" from their parent)

**Comment by javagl** [comment]
Should be fixed with https://github.com/CesiumGS/3d-tiles-samples/pull/45
