### ISSUE TITLE
Question: Where to store `subtreeLevels` for tile that is a Child subtree?

### ISSUE THREAD

**Issue by wsw0108** [CesiumGS/3d-tiles-samples#58]
For example, if Tile `level3-5-0` also has child subtree like `level0-0-0` does, then can we also call `level3-5-0` an implicit root tile? 
If so, then where(which url?) to store `implicitTiling` object for tile/subtree-node `level3-5-0`?

https://github.com/CesiumGS/3d-tiles-samples/tree/main/1.1/SparseImplicitQuadtree#structure
https://github.com/CesiumGS/3d-tiles-samples/blob/main/1.1/SparseImplicitQuadtree/screenshot/subtreeInfo.md#coordinates-level3-5-0

**Comment by ptrgags** [comment]
Only a single `implicitTiling` object is needed in the `tileset.json`, regardless of how many child subtrees there are. The octree/quadtree subdivision scheme continues through the child subtrees.

Subtrees are just a way of dividing the hierarchy into smaller pieces so the runtime doesn't have to download availability for the entire tree at once.

**Comment by wsw0108** [comment]
Thanks for your quick answer.

Then in my opnion in generally the `availableLevels` should be multiple of `subtreeLevels`, as I see from the example mentioned above(6/3) or example from spec(https://github.com/CesiumGS/3d-tiles/blob/1.1/specification/ImplicitTiling/README.adoc#implicit-root-tile)(21/7).

**Comment by wsw0108** [comment]
@ptrgags Thanks for your kind and detail answer, now I totally understand.
